name: Matrix Configuration
on:
    push:
    workflow_dispatch:
jobs:
  deploy:
    strategy:
      fail-fast: false
      max-parallel: 2
      matrix:
        os: [Windows-latest,ubuntu-latest]
        images: [hello-world,alpine]
        exclude:
          - images: alpine
            os: Windows-latest
        include:
          - images: amd64/alpine
            os: ubuntu-20.04      
    runs-on: ${{matrix.os}}
    steps:
    - name: Echo Docker Details
      run: docker info
    - name: Run Images on ${{matrix.images}}
      run: docker run ${{matrix.images}}










    ### First RUN#####################
    # Deploys-on-ubuntu:
    #     runs-on: ubuntu-latest
    #     steps:
    #     - name: Echo Docker Details
    #       run: docker info
    #     - name: Run Images
    #       run: docker run hello-world
    # Deploys-on-Windows:
    #     runs-on: windows-latest
    #     steps:
    #     - name: Echo Docker Details
    #       run: docker info
    #     - name: Run Images
    #       run: docker run hello-world
        

