name: MultiJob
on: push
jobs:
    First_job:
        runs-on: ubuntu-latest
        steps:
            - name: Install Cowsay
              run: sudo apt-get install cowsay -y
            - name: Execute Cowsay Command
              run: cowsay -f dragon "Run For Cover, I am a Dragon....RAWR" >> dragon.txt
            - name: Upload Artifact
              uses: actions/upload-artifact@v4
              with:
                name: dragon-text-file
                path: dragon.txt
              
    Second_job:
        runs-on: ubuntu-latest
        needs: First_job
        steps:
            - name: Download the artifact
              uses: actions/download-artifact@v5
              with:
                name: dragon-text-file
            - name: List of Directories
              run: ls -ltra
            - name: Search for dragon
              run: grep -i "dragon" dragon.txt
    Third_job:
        runs-on: ubuntu-latest
        needs: [First_job,Second_job]
        steps:
            - name: Download the artifact
              uses: actions/download-artifact@v5
              with:
                name: dragon-text-file            
            - name: Read the Dragon text
              run: cat dragon.txt
            - name: Print the name
              run: echo "KRISHNA"
